# ─────────────────────
# General Configuration
# ─────────────────────
# Whether to send anonymous metrics using bstats.
Track-Metrics: true

Colors:
  Separator: "#555555"
  Primary: "#F77E21"
  Secondary: "#D1D1D1"
  Highlight: "#548CFF"
  Error-Primary: "#9B0000"
  Error-Secondary: "#FF7272"
  Error-Highlight: "#B22727"
  Success-Primary: "#52cd00"
  Success-Secondary: "#B8F1B0"
  Success-Highlight: "#4E944F"

# ───────────────────
# Redis Configuration
# ───────────────────
Server-ID: "Server"
Redis-Credentials:
  Host: ""
  Port: 6379
  Password: ""

# ────────────────────
# Hikari Configuration
# ────────────────────
Hikari-Details:
  Enabled: false
  Address: ""
  Database: ""
  Port: "3306"
  Username: "test"
  Password: "password"

# ──────────────────
# Menu Configuration
# ──────────────────
Confirmation-Menu:
  Title: "%question%"
  Size: 27
  Items:
    GreenPane:
      Slots: [ 0, 1, 2, 9, 11, 18, 19, 20 ]
      Material: "LIME_STAINED_GLASS_PANE"
      Name: "&aClick To Confirm"
    GrayPane:
      Slots: [ 3, 4, 5, 12, 14, 21, 22, 23 ]
      Material: "GRAY_STAINED_GLASS_PANE"
      Name: "&a"
    RedPane:
      Slots: [ 6, 7, 8, 15, 17, 24, 25, 26 ]
      Material: "RED_STAINED_GLASS_PANE"
      Name: "&cClick To Cancel"
    Confirm:
      Slot: 10
      Material: "LIME_STAINED_GLASS_PANE"
      Name: "&a&lConfirm"
    Info-Item:
      Slot: 13
      Material: "PLAYER_HEAD"
      Skull-Name: "MHF_Question"
      Name: "&a%question%"
    Cancel:
      Slot: 16
      Material: "RED_STAINED_GLASS_PANE"
      Name: "&c&lCancel"