# ─────────────────────
# General Configuration
# ─────────────────────
# Whether to send anonymous metrics using bstats.
Track-Metrics: true

Colors:
  Separator: "#555555"
  Primary: "#F77E21"
  Secondary: "#D1D1D1"
  Highlight: "#548CFF"
  Error-Primary: "#9B0000"
  Error-Secondary: "#FF7272"
  Error-Highlight: "#B22727"
  Success-Primary: "#52cd00"
  Success-Secondary: "#B8F1B0"
  Success-Highlight: "#4E944F"

# ───────────────────
# Redis Configuration
# ───────────────────
Server-ID: "Server"
Redis-Credentials:
  Host: ""
  Port: 6379
  Password: ""

# ────────────────────
# Hikari Configuration
# ────────────────────
Hikari-Details:
  Enabled: false
  Address: ""
  Database: ""
  Port: "3306"
  Username: "test"
  Password: "password"

# ──────────────────
# Menu Configuration
# ──────────────────
Confirmation-Menu:
  Title: "%question%"
  Size: 27
  Items:
    GreenPane:
      Slots: [ 0, 1, 2, 9, 11, 18, 19, 20 ]
      Material: "LIME_STAINED_GLASS_PANE"
      Name: "&aClick To Confirm"
    GrayPane:
      Slots: [ 3, 4, 5, 12, 14, 21, 22, 23 ]
      Material: "GRAY_STAINED_GLASS_PANE"
      Name: "&a"
    RedPane:
      Slots: [ 6, 7, 8, 15, 17, 24, 25, 26 ]
      Material: "RED_STAINED_GLASS_PANE"
      Name: "&cClick To Cancel"
    Confirm:
      Slot: 10
      Material: "LIME_STAINED_GLASS_PANE"
      Name: "&a&lConfirm"
    Info-Item:
      Slot: 13
      Material: "PLAYER_HEAD"
      Skull-Name: "MHF_Question"
      Name: "&a%question%"
    Cancel:
      Slot: 16
      Material: "RED_STAINED_GLASS_PANE"
      Name: "&c&lCancel"

# Armor Equip Ignored Materials
# These materials will not trigger the ArmorEquipEvent
# All blocks with an inventory or any blocks that when right-clicked shouldn't equip armor.
Ignored-Materials:
  - "FURNACE"
  - "CHEST"
  - "TRAPPED_CHEST"
  - "BEACON"
  - "DISPENSER"
  - "DROPPER"
  - "HOPPER"
  - "WORKBENCH"
  - "ENCHANTMENT_TABLE"
  - "ENDER_CHEST"
  - "ANVIL"
  - "BED_BLOCK"
  - "FENCE_GATE"
  - "SPRUCE_FENCE_GATE"
  - "BIRCH_FENCE_GATE"
  - "ACACIA_FENCE_GATE"
  - "JUNGLE_FENCE_GATE"
  - "DARK_OAK_FENCE_GATE"
  - "IRON_DOOR_BLOCK"
  - "WOODEN_DOOR"
  - "SPRUCE_DOOR"
  - "BIRCH_DOOR"
  - "JUNGLE_DOOR"
  - "ACACIA_DOOR"
  - "DARK_OAK_DOOR"
  - "WOOD_BUTTON"
  - "STONE_BUTTON"
  - "TRAP_DOOR"
  - "IRON_TRAPDOOR"
  - "DIODE_BLOCK_OFF"
  - "DIODE_BLOCK_ON"
  - "REDSTONE_COMPARATOR_OFF"
  - "REDSTONE_COMPARATOR_ON"
  - "FENCE"
  - "SPRUCE_FENCE"
  - "BIRCH_FENCE"
  - "JUNGLE_FENCE"
  - "DARK_OAK_FENCE"
  - "ACACIA_FENCE"
  - "NETHER_FENCE"
  - "BREWING_STAND"
  - "CAULDRON"
  - "LEGACY_SIGN_POST"
  - "LEGACY_WALL_SIGN"
  - "LEGACY_SIGN"
  - "ACACIA_SIGN"
  - "ACACIA_WALL_SIGN"
  - "BIRCH_SIGN"
  - "BIRCH_WALL_SIGN"
  - "DARK_OAK_SIGN"
  - "DARK_OAK_WALL_SIGN"
  - "JUNGLE_SIGN"
  - "JUNGLE_WALL_SIGN"
  - "OAK_SIGN"
  - "OAK_WALL_SIGN"
  - "SPRUCE_SIGN"
  - "SPRUCE_WALL_SIGN"
  - "LEVER"
  - "BLACK_SHULKER_BOX"
  - "BLUE_SHULKER_BOX"
  - "BROWN_SHULKER_BOX"
  - "CYAN_SHULKER_BOX"
  - "GRAY_SHULKER_BOX"
  - "GREEN_SHULKER_BOX"
  - "LIGHT_BLUE_SHULKER_BOX"
  - "LIME_SHULKER_BOX"
  - "MAGENTA_SHULKER_BOX"
  - "ORANGE_SHULKER_BOX"
  - "PINK_SHULKER_BOX"
  - "PURPLE_SHULKER_BOX"
  - "RED_SHULKER_BOX"
  - "SILVER_SHULKER_BOX"
  - "WHITE_SHULKER_BOX"
  - "YELLOW_SHULKER_BOX"
  - "DAYLIGHT_DETECTOR_INVERTED"
  - "DAYLIGHT_DETECTOR"
  - "BARREL"
  - "BLAST_FURNACE"
  - "SMOKER"
  - "CARTOGRAPHY_TABLE"
  - "COMPOSTER"
  - "GRINDSTONE"
  - "LECTERN"
  - "LOOM"
  - "STONECUTTER"
  - "BELL"