name: JustAPI
version: ${project.version}
main: net.justugh.japi.JustAPIPlugin
api-version: 1.17
authors: [ Justugh ]
description: An API with various features for making stuff easier.
website: https://www.justugh.net
commands:
  justapi:
